### ISSUE TITLE
rule errors

### ISSUE THREAD

**Issue by SwissResl** [pimatic/pimatic-mail#8] opened 2016-12-01 21:33 UTC
I'm getting following errors:
`error [pimatic]: Error on evaluation of rule condition of rule sendmail: __ is not defined
error [pimatic]: rule sendmail error executing an action: __ is not defined`

Rule:
`  "rules": [
    {
      "id": "sendmail",
      "name": "SendTestmail",
      "rule": "when relais-2 is turned on then send mail",
      "active": true,
      "logging": true
    }
  ],`

mail config:
`      "plugin": "mail",
      "transport": "sendmail",
      "transportOptions": {
        "host": "mail.smtp.com",
        "port": "465",
        "secureConnection": true,
        "requiresAuth": true,
        "auth": {
          "user": "test@test.com",
          "pass": "*************"
        }
      },
      "from": "test@test.com",
      "to": "test@test.com",
      "active": true
`

**Comment by mwittig** [comment] 2018-01-29 17:59
The problem appears to be with rule condition rather than the mail action provider! If you still experience this issue please test the condition with another action. 
For the time being I assume the issue is osbolete and I am closing this now. 
Please re-open if you wish to follow-up.

**Closed as completed by mwittig** 2018-01-29 17:59 UTC
